「Railsでテストを書く」の課題を作成しました
a-kuroki-gs/fjord-books_app-2023 pull request #7
Opened 2023-11-15 06:26 UTC by a-kuroki-gs

2023-11-20 15:09 UTC, u1tnk requested changes

2023-11-20 15:09 UTC, u1tnk commented on test/fixtures/books.yml
> +# one:
基本的に不要なコードをコメントアウトはしません。削除しましょう。全部消えたらファイルを消しましょう。

2023-11-20 15:09 UTC, u1tnk commented on test/system/reports_test.rb
> +    assert_text '日報が作成されました。'
作成されましたのメッセージだけでなく、データが増えていることを確認しましょう

2023-11-20 15:09 UTC, u1tnk commented on test/system/reports_test.rb
> +    click_on '日報の一覧に戻る'
最後に戻る必要は無いと思います。

2023-11-21 06:12 UTC, a-kuroki-gs commented on test/fixtures/books.yml
> +# one:
不要なファイルを削除しました。

2023-11-21 06:12 UTC, a-kuroki-gs commented on test/system/reports_test.rb
> +    assert_text '日報が作成されました。'
- データが表示されているか
- `h1`タグが表示されているか

のテストを追加しました。

2023-11-21 06:12 UTC, a-kuroki-gs commented on test/system/reports_test.rb
> +    click_on '日報の一覧に戻る'
戻る部分を削除しました。

2023-11-21 13:50 UTC, u1tnk requested changes

2023-11-21 13:50 UTC, u1tnk commented on test/system/reports_test.rb
> +    assert_selector 'h1', text: '日報の一覧'
ここは削除された日報のタイトル文字列が無い、もしくはデータベース上になくなっているなどで確認しましょう。

2023-11-24 01:45 UTC, a-kuroki-gs commented on test/system/reports_test.rb
> +    assert_selector 'h1', text: '日報の一覧'
日報削除後に、日報が存在しないかをテストする処理を追加しました。

2023-11-24 16:13 UTC, u1tnk approved these changes

2023-11-26 23:52 UTC, merged